name: Go
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.x.x, 1.18.x, 1.17.x, 1.16.x, 1.15.x, 1.14.x, 1.13.x, 1.12.x, 1.11.x, 1.10.x, 1.9.x, 1.8.x, 1.7.x, 1.6.x, 1.5.x, 1.4.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v3
    - run: |
      go fmt ./...
      make test
      make coveralls
      bash <(curl -s https://codecov.io/bash)
